### ISSUE TITLE
Failing to resolve card ids when querying NRDB

### ISSUE THREAD

**Issue by danieljluna** [mangofeet/nrdb-go#1]
This issue was found while using netrunner-alt-gen.

Namely, attempting to pass in a card id # instead of the card name always seems to fail. This behavior seems to have been recently introduced, as this feature was working a few weeks ago - namely August 3rd was the last successful use.

Below is an example repro from command line usage. The local folder space is netrunner-alt-gen. Note that the card id of Noise is 1.

```
> go run . empty 1
error: no result for printing ID 1
exit status 1
> go run . empty Noise
generating Noise: Hacker Extraordinaire
Card: Noise: Hacker Extraordinaire, type: runner_identity
rendering output to output/001001-core-set-001-noise-hacker-extraordinaire.png
done
```

**Comment by mangofeet** [comment]
the ID is different than that, the printing ID in NRDB for Noise is `01001` (you can see this in the card's URL https://netrunnerdb.com/en/card/01001)
